sudo: required

services:
  - docker
env:
  - IMAGE_NAME=win-test/angular
  
language: bash

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
cache:
  bundler: true
  directories:
    - $HOME/docker
  
# addons:
#   apt:
#     packages:
#       - docker-ce

before_script:
  - docker -v


script: 
  - git_sha="$(git rev-parse --short HEAD)"
  - docker build --cache-from $IMAGE_NAME:latest --build-arg BUILDKIT_INLINE_CACHE=1  -t $IMAGE_NAME:latest  .
